name       : kmix
version    : 18.04.0
release    : 4
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.0/src/kmix-18.04.0.tar.xz : af260816fcaa9bcd7ddb13e16b331479b55aa759c0a2c1202d69c96c4b930577
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.0
component  : desktkop.kde
optimize   : lto
libsplit   : no
summary    : KDE volume control program
description: |
    KDE volume control program.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gl)
    - pkgconfig(libcanberra)
    - pkgconfig(libpulse)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdbusaddons-devel
    - kdelibs4support-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kxmlgui-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
