name       : kmix
version    : 19.08.2
release    : 23
source     :
    - https://download.kde.org/stable/applications/19.08.2/src/kmix-19.08.2.tar.xz : 5d852df8b54d3abca98db4aa2b259973231fed0a597d511d54fb41c6389ce61a
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktkop.kde
summary    : KDE volume control program
description: |
    KDE volume control program.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(libcanberra)
    - pkgconfig(libpulse)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcrash-devel
    - kcompletion-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kiconthemes-devel
    - knotifications-devel
    - solid-devel
    - kxmlgui-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
