name       : kmix
version    : 18.08.1
release    : 9
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.1/src/kmix-18.08.1.tar.xz : f281ad91f1acae72e463215d7b8fd2f351b44914b13e2a314bb46a946b7bbcc4
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.0
component  : desktkop.kde
libsplit   : no
summary    : KDE volume control program
description: |
    KDE volume control program.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(libcanberra)
    - pkgconfig(libpulse)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdbusaddons-devel
    - kdelibs4support-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kxmlgui-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
