name       : kmix
version    : 18.04.3
release    : 7
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.3/src/kmix-18.04.3.tar.xz : 61bb02ccbef20168229be722be68f697e60555f9a352e699c6ad6b462ef18e3d
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.0
component  : desktkop.kde
libsplit   : no
summary    : KDE volume control program
description: |
    KDE volume control program.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gl)
    - pkgconfig(libcanberra)
    - pkgconfig(libpulse)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdbusaddons-devel
    - kdelibs4support-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kxmlgui-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
