name       : kmix
version    : 18.12.3
release    : 15
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.3/src/kmix-18.12.3.tar.xz : 4edf31a36a5d700cc190ba7a5a0d76789729069d48324a22bda7977cb4ed081a
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktkop.kde
summary    : KDE volume control program
description: |
    KDE volume control program.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(libcanberra)
    - pkgconfig(libpulse)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdbusaddons-devel
    - kdelibs4support-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kxmlgui-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
