name       : kmix
version    : 18.04.2
release    : 6
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.2/src/kmix-18.04.2.tar.xz : a7d6027fe79948616091e694a1a0284cecde90d50b2cef3b4c7559983bc74fd0
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.0
component  : desktkop.kde
libsplit   : no
summary    : KDE volume control program
description: |
    KDE volume control program.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gl)
    - pkgconfig(libcanberra)
    - pkgconfig(libpulse)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdbusaddons-devel
    - kdelibs4support-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kxmlgui-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
