name       : kmix
version    : 20.12.3
release    : 44
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.3/src/kmix-20.12.3.tar.xz : 68f892958eec984685567ad36624084118b6dc5e7a4633733a6c3e6aea34ea17
homepage   : https://kde.org/applications/multimedia/org.kde.kmix
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktkop.kde
summary    : KDE volume control program
description: |
    KDE volume control program.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(libcanberra)
    - pkgconfig(libpulse)
    - kcrash-devel
    - kcompletion-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kiconthemes-devel
    - knotifications-devel
    - solid-devel
    - kxmlgui-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
